// Test fixtures for date-night modifier Playwright tests.
// These are isolated to tests and do not affect production behavior.
// To use: set NEXT_PUBLIC_TEST_MODE=1

import type { Venue } from "./types";

export const TEST_FIXTURES = {
  ubud: {
    districtSlug: "ubud",
    districtName: "Ubud",
    venues: [
      // 4 special-occasion venues
      {
        id: "test-ubud-1",
        slug: "ubud-romantic-1",
        name: "Test Ubud Special Occasion 1",
        category: "restaurant" as const,
        district: "ubud",
        address: "Test Address 1, Ubud",
        gmapsUrl: "https://maps.google.com/ubud-1",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special", "special_occasion"],
      },
      {
        id: "test-ubud-2",
        slug: "ubud-romantic-2",
        name: "Test Ubud Special Occasion 2",
        category: "restaurant" as const,
        district: "ubud",
        address: "Test Address 2, Ubud",
        gmapsUrl: "https://maps.google.com/ubud-2",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special", "special_occasion"],
      },
      {
        id: "test-ubud-3",
        slug: "ubud-romantic-3",
        name: "Test Ubud Special Occasion 3",
        category: "restaurant" as const,
        district: "ubud",
        address: "Test Address 3, Ubud",
        gmapsUrl: "https://maps.google.com/ubud-3",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special", "special_occasion"],
      },
      {
        id: "test-ubud-4",
        slug: "ubud-romantic-4",
        name: "Test Ubud Special Occasion 4",
        category: "restaurant" as const,
        district: "ubud",
        address: "Test Address 4, Ubud",
        gmapsUrl: "https://maps.google.com/ubud-4",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special", "special_occasion"],
      },
      // 2 sunset-view venues
      {
        id: "test-ubud-5",
        slug: "ubud-sunset-1",
        name: "Test Ubud Sunset View 1",
        category: "restaurant" as const,
        district: "ubud",
        address: "Test Address 5, Ubud",
        gmapsUrl: "https://maps.google.com/ubud-5",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special", "sunset_drinks_view"],
      },
      {
        id: "test-ubud-6",
        slug: "ubud-sunset-2",
        name: "Test Ubud Sunset View 2",
        category: "restaurant" as const,
        district: "ubud",
        address: "Test Address 6, Ubud",
        gmapsUrl: "https://maps.google.com/ubud-6",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special", "sunset_drinks_view"],
      },
      // 3 venues with no special modifiers
      {
        id: "test-ubud-7",
        slug: "ubud-regular-1",
        name: "Test Ubud Regular 1",
        category: "restaurant" as const,
        district: "ubud",
        address: "Test Address 7, Ubud",
        gmapsUrl: "https://maps.google.com/ubud-7",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special"],
      },
      {
        id: "test-ubud-8",
        slug: "ubud-regular-2",
        name: "Test Ubud Regular 2",
        category: "restaurant" as const,
        district: "ubud",
        address: "Test Address 8, Ubud",
        gmapsUrl: "https://maps.google.com/ubud-8",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special"],
      },
      {
        id: "test-ubud-9",
        slug: "ubud-regular-3",
        name: "Test Ubud Regular 3",
        category: "restaurant" as const,
        district: "ubud",
        address: "Test Address 9, Ubud",
        gmapsUrl: "https://maps.google.com/ubud-9",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special"],
      },
    ] as Venue[],
  },
  "uluwatu-bukit": {
    districtSlug: "uluwatu-bukit",
    districtName: "Uluwatu & Bukit",
    venues: [
      // 7 quiet venues
      {
        id: "test-uluwatu-1",
        slug: "uluwatu-quiet-1",
        name: "Test Uluwatu Quiet 1",
        category: "restaurant" as const,
        district: "uluwatu-bukit",
        address: "Test Address 1, Uluwatu",
        gmapsUrl: "https://maps.google.com/uluwatu-1",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special"],
        vibeTags: ["quiet"],
      },
      {
        id: "test-uluwatu-2",
        slug: "uluwatu-quiet-2",
        name: "Test Uluwatu Quiet 2",
        category: "restaurant" as const,
        district: "uluwatu-bukit",
        address: "Test Address 2, Uluwatu",
        gmapsUrl: "https://maps.google.com/uluwatu-2",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special"],
        vibeTags: ["quiet"],
      },
      {
        id: "test-uluwatu-3",
        slug: "uluwatu-quiet-3",
        name: "Test Uluwatu Quiet 3",
        category: "restaurant" as const,
        district: "uluwatu-bukit",
        address: "Test Address 3, Uluwatu",
        gmapsUrl: "https://maps.google.com/uluwatu-3",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special"],
        vibeTags: ["quiet"],
      },
      {
        id: "test-uluwatu-4",
        slug: "uluwatu-quiet-4",
        name: "Test Uluwatu Quiet 4",
        category: "restaurant" as const,
        district: "uluwatu-bukit",
        address: "Test Address 4, Uluwatu",
        gmapsUrl: "https://maps.google.com/uluwatu-4",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special"],
        vibeTags: ["quiet"],
      },
      {
        id: "test-uluwatu-5",
        slug: "uluwatu-quiet-5",
        name: "Test Uluwatu Quiet 5",
        category: "restaurant" as const,
        district: "uluwatu-bukit",
        address: "Test Address 5, Uluwatu",
        gmapsUrl: "https://maps.google.com/uluwatu-5",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special"],
        vibeTags: ["quiet"],
      },
      {
        id: "test-uluwatu-6",
        slug: "uluwatu-quiet-6",
        name: "Test Uluwatu Quiet 6",
        category: "restaurant" as const,
        district: "uluwatu-bukit",
        address: "Test Address 6, Uluwatu",
        gmapsUrl: "https://maps.google.com/uluwatu-6",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special"],
        vibeTags: ["quiet"],
      },
      {
        id: "test-uluwatu-7",
        slug: "uluwatu-quiet-7",
        name: "Test Uluwatu Quiet 7",
        category: "restaurant" as const,
        district: "uluwatu-bukit",
        address: "Test Address 7, Uluwatu",
        gmapsUrl: "https://maps.google.com/uluwatu-7",
        tier: "editorial_seed" as const,
        isSponsored: false,
        publicationStatus: "published" as const,
        jobs: ["date_night_special"],
        vibeTags: ["quiet"],
      },
    ] as Venue[],
  },
};
