ext {
    mapboxNavigationVersion = project.hasProperty('mapboxNavigationVersion') ? rootProject.ext.mapboxNavigationVersion : '3.26.0'
}
buildscript { repositories { google(); mavenCentral() } }
apply plugin: 'com.android.library'
android {
    namespace "com.otherbali.offlinemapbox"
    compileSdk project.hasProperty('compileSdkVersion') ? rootProject.ext.compileSdkVersion : 36
    defaultConfig { minSdk project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 24 }
    compileOptions { sourceCompatibility JavaVersion.VERSION_21; targetCompatibility JavaVersion.VERSION_21 }
}
dependencies {
    implementation project(':capacitor-android')
    implementation "com.mapbox.navigationcore:android-ndk27:$mapboxNavigationVersion"
    implementation "com.mapbox.maps:android-ndk27:11.26.0"
}
