-- Deepen the five-district public planning layer with safe editorial fields.
-- Source files: raw_otherbali_longlist_master_5districts_v0.2.csv plus
-- verify/gaps handoff CSVs (2026-07-11 exports).
-- Source rows scanned: 88. Actionable public-safe updates: 74.
--
-- Guardrails:
-- - This updates existing venue rows only; it does not add perks, QR posters,
--   plan_entries, TablePilot slugs, tourist payments, or paid ranking.
-- - Ratings, review counts, TripAdvisor ranks, complaints, red flags,
--   confidence scores, and internal verify notes are intentionally not imported.
-- - Russian/internal concept text is not published directly. Public copy is
--   derived only from safe category, district, vibe, JTBD, price band, and
--   signature fields.
-- - Existing richer public fields from earlier migrations win over this fill-in
--   layer; this migration mainly deepens rows that were imported as bare cards.

with deep_updates(slug, vibe_tags, jobs, price_anchor, why_its_here, best_for, what_to_order) as (
values
  ('cuca-restaurant', array['romantic', 'quiet', 'lively']::text[], array['date_night_special', 'special_occasion']::text[], 'Price band: $$$', 'A Jimbaran restaurant for date night and special occasion.', 'date night and special occasion', 'white-fish ceviche; stuffed satay chicken; beef bone + garlic sticky rice'),
  ('sundara', array['view', 'romantic', 'lively', 'family']::text[], array['sunset_drinks_view', 'date_night_special', 'special_occasion', 'family_early_dinner']::text[], 'Price band: $$$', 'A Jimbaran beach club for sunset drinks with a view, date night, special occasion, and early family dinner.', 'sunset drinks with a view, date night, special occasion, and early family dinner', 'tuna tartare; wagyu tataki; crispy baby pig'),
  ('kayumanis-resto-jimbaran', array['quiet', 'family', 'romantic']::text[], array['just_landed_easy_dinner', 'family_early_dinner', 'group_dinner_share']::text[], 'Price band: $$', 'A Jimbaran restaurant for easy first-night dinner, early family dinner, and group dinner.', 'easy first-night dinner, early family dinner, and group dinner', 'Indonesian share platters; grilled seafood; classic mains'),
  ('balique-restaurant', array['quiet', 'family', 'romantic']::text[], array['family_early_dinner', 'local_food_calm', 'group_dinner_share']::text[], 'Price band: $$', 'A Jimbaran cafe for early family dinner, calm local food, and group dinner.', 'early family dinner, calm local food, and group dinner', 'rijsttafel; nasi campur; beef rendang'),
  ('dava-steak-and-seafood', array['quiet', 'romantic', 'view']::text[], array['date_night_special', 'special_occasion']::text[], 'Price band: $$$', 'A Jimbaran restaurant for date night and special occasion.', 'date night and special occasion', 'wagyu steak; dry-aged striploin; seafood mains'),
  ('unique-rooftop-bar-and-restaurant', array['lively', 'view', 'romantic']::text[], array['sunset_drinks_view', 'group_dinner_share', 'date_night_special']::text[], 'Price band: $$$', 'A Jimbaran bar and restaurant for sunset drinks with a view, group dinner, and date night.', 'sunset drinks with a view, group dinner, and date night', 'prawn tacos; fajitas; margaritas'),
  ('bella-cucina', array['romantic', 'quiet']::text[], array['date_night_special', 'special_occasion']::text[], 'Price band: $$$', 'A Jimbaran restaurant for date night and special occasion.', 'date night and special occasion', 'handmade pasta; Mediterranean mains'),
  ('sunset-beach-bar-and-grill', array['view', 'family', 'lively']::text[], array['sunset_drinks_view', 'family_early_dinner', 'just_landed_easy_dinner']::text[], 'Price band: $$', 'A Jimbaran bar and restaurant for sunset drinks with a view, early family dinner, and easy first-night dinner.', 'sunset drinks with a view, early family dinner, and easy first-night dinner', 'cocktails; beach-grill mains'),
  ('akua-mediterranean', array['romantic', 'view', 'lively']::text[], array['date_night_special', 'sunset_drinks_view']::text[], 'Price band: $$', 'A Jimbaran bar and restaurant for date night and sunset drinks with a view.', 'date night and sunset drinks with a view', 'black-ink paella; barramundi; Basque cheesecake'),
  ('nelayan-restaurant-and-puri-bar', array['romantic', 'view', 'quiet']::text[], array['date_night_special', 'sunset_drinks_view', 'special_occasion']::text[], 'Price band: $$$', 'A Jimbaran bar and restaurant for date night, sunset drinks with a view, and special occasion.', 'date night, sunset drinks with a view, and special occasion', 'seafood Indo-Med/French; cocktails'),
  ('bawang-merah-beachfront', array['lively', 'family', 'view']::text[], array['group_dinner_share', 'family_early_dinner', 'sunset_drinks_view']::text[], 'Price band: $$', 'A Jimbaran restaurant for group dinner, early family dinner, and sunset drinks with a view.', 'group dinner, early family dinner, and sunset drinks with a view', 'Seafood Maharani set; grilled platters; ayam sambal bawang'),
  ('ko-japanese-teppanyaki-and-sushi', array['family', 'lively', 'quiet']::text[], array['family_early_dinner', 'special_occasion', 'group_dinner_share']::text[], 'Price band: $$$', 'A Jimbaran restaurant for early family dinner, special occasion, and group dinner.', 'early family dinner, special occasion, and group dinner', 'teppanyaki seafood; sushi; grilled meats'),
  ('warung-mami-ikan-bakar', array['lively', 'family']::text[], array['local_food_calm', 'group_dinner_share', 'just_landed_easy_dinner']::text[], 'Price band: $$', 'A Jimbaran warung for calm local food, group dinner, and easy first-night dinner.', 'calm local food, group dinner, and easy first-night dinner', 'grilled fish; prawns; clams sambal matah'),
  ('radja-seafood-cafe', array['view', 'lively', 'family']::text[], array['sunset_drinks_view', 'group_dinner_share', 'family_early_dinner']::text[], 'Price band: $$', 'A Jimbaran restaurant for sunset drinks with a view, group dinner, and early family dinner.', 'sunset drinks with a view, group dinner, and early family dinner', 'grilled fish; shellfish; seafood sets'),
  ('nyoman-cafe', array['lively', 'view', 'family']::text[], array['group_dinner_share', 'sunset_drinks_view', 'family_early_dinner']::text[], 'Price band: $$', 'A Jimbaran restaurant for group dinner, sunset drinks with a view, and early family dinner.', 'group dinner, sunset drinks with a view, and early family dinner', 'grilled seafood; set menus; crab/prawn combos'),
  ('warung-ramayana-ikan-bakar', array['lively', 'view']::text[], array['group_dinner_share', 'sunset_drinks_view']::text[], 'Price band: $$', 'A Jimbaran warung for group dinner and sunset drinks with a view.', 'group dinner and sunset drinks with a view', 'grilled red snapper; black-pepper crab; BBQ clams'),
  ('merah-putih-indonesian-restaurant', null::text[], array['date_night_special']::text[], 'Price band: $$$', 'A Seminyak restaurant for date night.', 'date night', 'beef cheeks'),
  ('potato-head-beach-club', null::text[], array['sunset_drinks_view']::text[], 'Price band: $$$', 'A Seminyak beach club for sunset drinks with a view.', 'sunset drinks with a view', 'chicken wings'),
  ('mamasan-bali', null::text[], array['group_dinner_share']::text[], 'Price band: $$$', 'A Seminyak restaurant for group dinner.', 'group dinner', 'soft-shell crab; peking duck; pork belly'),
  ('mauri-restaurant', null::text[], null::text[], 'Price band: $$$', null, null, 'risotto'),
  ('bambu', null::text[], array['date_night_special']::text[], 'Price band: $$$', 'A Seminyak restaurant for date night.', 'date night', 'pork ribs; grilled prawns; dadar gulung'),
  ('sisterfields', null::text[], array['brunch_after_surf']::text[], 'Price band: $$', 'A Seminyak cafe for brunch after surf.', 'brunch after surf', 'eggs benedict; truffle scrambled; pancakes'),
  ('waroeng-bernadette', null::text[], array['local_food_calm']::text[], 'Price band: $$', 'A Seminyak warung for calm local food.', 'calm local food', 'beef rendang; oxtail stew; chicken satay'),
  ('warung-nia-balinese-food-and-pork-ribs', null::text[], array['local_food_calm']::text[], 'Price band: $$', 'A Seminyak warung for calm local food.', 'calm local food', 'pork ribs; chicken satay; banana pancakes'),
  ('biku', null::text[], array['brunch_after_surf']::text[], 'Price band: $$$', 'A Seminyak cafe for brunch after surf.', 'brunch after surf', 'nasi campur; rendang; high tea'),
  ('kilo-kitchen-bali-seminyak', null::text[], array['group_dinner_share']::text[], 'Price band: $$$', 'A Seminyak restaurant for group dinner.', 'group dinner', 'truffled tai yuzu roll; squid ink rice; beef cheek'),
  ('ling-lings-bali', null::text[], array['group_dinner_share']::text[], 'Price band: $$', 'A Seminyak bar and restaurant for group dinner.', 'group dinner', 'tuna tartar nachos; bao/tacos; coconut brulee'),
  ('ginger-moon-canteen', null::text[], null::text[], 'Price band: $$', null, null, 'prawn dumplings; barramundi buns; babi guling buns'),
  ('sea-circus', null::text[], array['brunch_after_surf']::text[], 'Price band: $$', 'A Seminyak cafe for brunch after surf.', 'brunch after surf', 'fish tacos; acai bowls; corn fritters'),
  ('sardine', null::text[], array['date_night_special']::text[], 'Price band: $$$', 'A Seminyak restaurant for date night.', 'date night', 'grilled sardine; octopus; lobster linguine'),
  ('boyncow', null::text[], array['group_dinner_share', 'special_occasion']::text[], 'Price band: $$$', 'A Seminyak restaurant for group dinner and special occasion.', 'group dinner and special occasion', 'dry-aged ribeye; tomahawk; bone marrow'),
  ('sangsaka', null::text[], array['date_night_special']::text[], 'Price band: $$$', 'A Seminyak restaurant for date night.', 'date night', 'shrimp dumplings; lobster bisque; smoked duck'),
  ('pison-petitenget', null::text[], array['brunch_after_surf']::text[], 'Price band: $$', 'A Seminyak cafe for brunch after surf.', 'brunch after surf', 'oxtail; fried chicken; apple pie'),
  ('gooseberry-french-restaurant-uluwatu', array['quiet', 'romantic', 'family']::text[], array['group_dinner_share', 'date_night_special', 'special_occasion']::text[], 'Price band: $$$', 'A Uluwatu and the Bukit restaurant for group dinner, date night, and special occasion.', 'group dinner, date night, and special occasion', 'onglet steak'),
  ('suka-espresso', array['lively', 'work-friendly']::text[], array['brunch_after_surf']::text[], 'Price band: $$', 'A Uluwatu and the Bukit cafe for brunch after surf.', 'brunch after surf', 'truffle scramble; specialty coffee'),
  ('masonry-restaurant', array['romantic', 'lively']::text[], array['group_dinner_share', 'date_night_special']::text[], 'Price band: $$$', 'A Uluwatu and the Bukit restaurant for group dinner and date night.', 'group dinner and date night', null),
  ('artisan-uluwatu', array['lively', 'romantic', 'work-friendly']::text[], array['brunch_after_surf', 'date_night_special']::text[], 'Price band: $$', 'A Uluwatu and the Bukit cafe for brunch after surf and date night.', 'brunch after surf and date night', 'stuffed bagels; scrambled+sourdough'),
  ('ulu-artisan-ungasan', array['work-friendly', 'family']::text[], array['brunch_after_surf', 'quiet_work_cafe']::text[], 'Price band: $$', 'A Uluwatu and the Bukit cafe for brunch after surf and quiet work session.', 'brunch after surf and quiet work session', 'bagels; pancakes; brunch plates'),
  ('alchemy-uluwatu', array['quiet', 'work-friendly']::text[], array['brunch_after_surf', 'quiet_work_cafe']::text[], 'Price band: $$', 'A Uluwatu and the Bukit cafe for brunch after surf and quiet work session.', 'brunch after surf and quiet work session', 'bowls; jackfruit salad; pizza/kombucha'),
  ('bgs-uluwatu', array['work-friendly', 'quiet']::text[], array['brunch_after_surf', 'quiet_work_cafe']::text[], 'Price band: $', 'A Uluwatu and the Bukit cafe for brunch after surf and quiet work session.', 'brunch after surf and quiet work session', 'almond latte; light bites; bakery'),
  ('yuki-uluwatu', array['lively', 'romantic']::text[], array['date_night_special', 'special_occasion', 'group_dinner_share']::text[], 'Price band: $$$', 'A Uluwatu and the Bukit restaurant for date night, special occasion, and group dinner.', 'date night, special occasion, and group dinner', 'torched salmon maki; wagyu sando; tuna tartare'),
  ('mana-uluwatu', array['view', 'romantic', 'family']::text[], array['sunset_drinks_view', 'date_night_special', 'family_early_dinner']::text[], 'Price band: $$$', 'A Uluwatu and the Bukit bar and restaurant for sunset drinks with a view, date night, and early family dinner.', 'sunset drinks with a view, date night, and early family dinner', 'potato bravas; baja tacos; roasted chicken'),
  ('ulu-fishmarket', array['family', 'lively']::text[], array['family_early_dinner', 'group_dinner_share']::text[], 'Price band: $$', 'A Uluwatu and the Bukit restaurant for early family dinner and group dinner.', 'early family dinner and group dinner', 'sashimi trio; tuna tataki; miso ramen'),
  ('seed-bingin', array['quiet', 'romantic']::text[], array['date_night_special', 'group_dinner_share']::text[], 'Price band: $$', 'A Uluwatu and the Bukit restaurant for date night and group dinner.', 'date night and group dinner', 'beef rendang; creme brulee; seasonal plates'),
  ('son-of-a-baker', array['work-friendly', 'quiet']::text[], array['brunch_after_surf', 'quiet_work_cafe']::text[], 'Price band: $$', 'A Uluwatu and the Bukit cafe for brunch after surf and quiet work session.', 'brunch after surf and quiet work session', 'artisanal bakes; Italian coffee; pumpkin-seed latte'),
  ('papi-sapi', array['lively', 'romantic']::text[], array['group_dinner_share', 'date_night_special']::text[], 'Price band: $$$', 'A Uluwatu and the Bukit restaurant for group dinner and date night.', 'group dinner and date night', 'premium grills; wagyu rib eye; picanha'),
  ('kala-uluwatu', array['lively', 'romantic']::text[], array['date_night_special', 'group_dinner_share']::text[], 'Price band: $$$', 'A Uluwatu and the Bukit restaurant for date night and group dinner.', 'date night and group dinner', 'wood-fired flatbreads; feta tempura; lamb'),
  ('laggas-uluwatu', array['lively', 'family']::text[], array['group_dinner_share', 'family_early_dinner']::text[], 'Price band: $$', 'A Uluwatu and the Bukit restaurant for group dinner and early family dinner.', 'group dinner and early family dinner', 'dumplings; noodles; slow-cooked ribs'),
  ('single-fin', array['lively', 'view']::text[], array['sunset_drinks_view', 'group_dinner_share']::text[], 'Price band: $$', 'A Uluwatu and the Bukit bar and restaurant for sunset drinks with a view and group dinner.', 'sunset drinks with a view and group dinner', 'bread&dip; chicken wings; calamari'),
  ('el-kabron-bali', array['lively', 'romantic', 'view']::text[], array['sunset_drinks_view', 'special_occasion', 'date_night_special']::text[], 'Price band: $$$', 'A Uluwatu and the Bukit beach club for sunset drinks with a view, special occasion, and date night.', 'sunset drinks with a view, special occasion, and date night', 'oysters; tomahawk'),
  ('sundays-beach-club', array['view', 'family', 'lively']::text[], array['sunset_drinks_view', 'family_early_dinner', 'special_occasion']::text[], 'Price band: $$$', 'A Uluwatu and the Bukit beach club for sunset drinks with a view, early family dinner, and special occasion.', 'sunset drinks with a view, early family dinner, and special occasion', 'mahi mahi tacos; BBQ lobster; wood-fired pizza'),
  ('tropical-temptation-adult-only-beach-club', array['lively', 'view']::text[], array['sunset_drinks_view', 'group_dinner_share']::text[], 'Price band: $$$', 'A Uluwatu and the Bukit beach club for sunset drinks with a view and group dinner.', 'sunset drinks with a view and group dinner', null),
  ('the-warung-at-alila-villas-uluwatu', array['romantic', 'view', 'quiet']::text[], array['special_occasion', 'date_night_special']::text[], 'Price band: $$$', 'A Uluwatu and the Bukit restaurant for special occasion and date night.', 'special occasion and date night', 'nasi campur; ayam betutu; sambal set'),
  ('ulu-garden', array['lively', 'family']::text[], array['group_dinner_share', 'family_early_dinner']::text[], 'Price band: $$', 'A Uluwatu and the Bukit restaurant for group dinner and early family dinner.', 'group dinner and early family dinner', 'miso gnocchi; ulu fresh rolls; rice bowl'),
  ('waatu', array['romantic', 'view', 'quiet']::text[], array['date_night_special', 'sunset_drinks_view', 'special_occasion']::text[], 'Price band: $$$', 'A Uluwatu and the Bukit restaurant for date night, sunset drinks with a view, and special occasion.', 'date night, sunset drinks with a view, and special occasion', 'fire-cooked local produce; yakitori'),
  ('kayuputi', array['romantic', 'view', 'quiet']::text[], array['date_night_special', 'special_occasion']::text[], 'Price band: $$$', 'A Nusa Dua restaurant for date night and special occasion.', 'date night and special occasion', 'grilled octopus; Hokkaido scallops; lobster'),
  ('koral', array['romantic', 'lively', 'view']::text[], array['special_occasion', 'date_night_special']::text[], 'Price band: $$$', 'A Nusa Dua restaurant for special occasion and date night.', 'special occasion and date night', '6/8-course tasting; pairings'),
  ('izakaya-by-oku', array['romantic', 'lively']::text[], array['date_night_special', 'special_occasion']::text[], 'Price band: $$$', 'A Nusa Dua restaurant for date night and special occasion.', 'date night and special occasion', 'fresh sushi; karaage twist; set menus'),
  ('manarai-beach-house', array['view', 'family', 'lively']::text[], array['sunset_drinks_view', 'family_early_dinner', 'just_landed_easy_dinner']::text[], 'Price band: $$', 'A Nusa Dua beach club for sunset drinks with a view, early family dinner, and easy first-night dinner.', 'sunset drinks with a view, early family dinner, and easy first-night dinner', 'wagyu skewers; pork ribs; tuna bowl'),
  ('bumbu-bali', array['family', 'quiet']::text[], array['local_food_calm', 'group_dinner_share', 'family_early_dinner']::text[], 'Price band: $$', 'A Nusa Dua restaurant for calm local food, group dinner, and early family dinner.', 'calm local food, group dinner, and early family dinner', 'rijsttafel; satay platters; rendang'),
  ('soleil-at-mulia', array['romantic', 'family', 'view']::text[], array['special_occasion', 'family_early_dinner', 'date_night_special']::text[], 'Price band: $$$', 'A Nusa Dua restaurant for special occasion, early family dinner, and date night.', 'special occasion, early family dinner, and date night', 'brunch seafood tower; carbonara; salmon'),
  ('arwana', array['romantic', 'view', 'family']::text[], array['date_night_special', 'special_occasion', 'family_early_dinner']::text[], 'Price band: $$$', 'A Nusa Dua restaurant for date night, special occasion, and early family dinner.', 'date night, special occasion, and early family dinner', 'scallops; barramundi; grilled lobster'),
  ('the-beach-grill-ritz-carlton', array['romantic', 'view']::text[], array['date_night_special', 'sunset_drinks_view', 'special_occasion']::text[], 'Price band: $$$', 'A Nusa Dua restaurant for date night, sunset drinks with a view, and special occasion.', 'date night, sunset drinks with a view, and special occasion', 'grilled lobster; wagyu; chili butter bread'),
  ('bejana-ritz-carlton', array['romantic', 'quiet', 'view']::text[], array['special_occasion', 'local_food_calm', 'date_night_special']::text[], 'Price band: $$$', 'A Nusa Dua restaurant for special occasion, calm local food, and date night.', 'special occasion, calm local food, and date night', 'rijsttafel; sambal cart; Indonesian sets'),
  ('piasan', array['quiet', 'romantic']::text[], array['date_night_special', 'quiet_work_cafe', 'special_occasion']::text[], 'Price band: $$$', 'A Nusa Dua restaurant for date night, quiet work session, and special occasion.', 'date night, quiet work session, and special occasion', 'zucchini flowers+crab; osso buco; penne alla vodka'),
  ('tetaring', array['quiet', 'family', 'romantic']::text[], array['local_food_calm', 'family_early_dinner', 'special_occasion']::text[], 'Price band: $$', 'A Nusa Dua restaurant for calm local food, early family dinner, and special occasion.', 'calm local food, early family dinner, and special occasion', 'crispy duck; soto ayam; seafood platter'),
  ('white-orchid-nusa-dua', array['family', 'quiet']::text[], array['family_early_dinner', 'just_landed_easy_dinner']::text[], 'Price band: $$', 'A Nusa Dua restaurant for early family dinner and easy first-night dinner.', 'early family dinner and easy first-night dinner', 'chicken satay; pad thai; seafood starters'),
  ('nusa-dua-beach-grill', array['view', 'family', 'quiet']::text[], array['family_early_dinner', 'local_food_calm', 'just_landed_easy_dinner']::text[], 'Price band: $$', 'A Nusa Dua restaurant for early family dinner, calm local food, and easy first-night dinner.', 'early family dinner, calm local food, and easy first-night dinner', 'grilled red snapper; lobster; fish platters'),
  ('warung-little-bird', null::text[], array['local_food_calm']::text[], null, 'A Sanur warung for calm local food.', 'calm local food', null),
  ('genius-cafe', array['work-friendly']::text[], array['quiet_work_cafe', 'brunch_after_surf']::text[], null, 'A Sanur cafe for quiet work session and brunch after surf.', 'quiet work session and brunch after surf', null),
  ('gong-restaurant', null::text[], array['special_occasion', 'date_night_special']::text[], null, 'A Sanur restaurant for special occasion and date night.', 'special occasion and date night', null),
  ('kuu-izakaya-dining', null::text[], array['date_night_special']::text[], null, 'A Sanur restaurant for date night.', 'date night', null),
  ('warung-coconut-tree', null::text[], array['local_food_calm']::text[], null, 'A Sanur warung for calm local food.', 'calm local food', null),
  ('warung-makan-little-mars', null::text[], array['local_food_calm']::text[], null, 'A Sanur warung for calm local food.', 'calm local food', null)
)
update public.venues as v set
  vibe_tags = coalesce(v.vibe_tags, d.vibe_tags),
  jobs = coalesce(v.jobs, d.jobs),
  price_anchor = coalesce(v.price_anchor, d.price_anchor),
  why_its_here = coalesce(v.why_its_here, d.why_its_here),
  best_for = coalesce(v.best_for, d.best_for),
  what_to_order = coalesce(v.what_to_order, d.what_to_order)
from deep_updates as d
where v.slug = d.slug;
