-- 0039_publish_kora_new_venues.sql
-- Insert 24 new Bali venues from the KORA prospects list as DECISION-READY rows:
-- researched street address + Google Maps link (web-research pass 2026-07-19) AND
-- editorial (why_its_here / best_for / not_for / what_to_order / price_anchor / area /
-- jobs), written in the Other Bali voice from official sites, menus and directories.
--
-- Guardrails held: no Google ratings/review counts; downsides only as fit-context
-- 'not_for'; prices as bands (never live menus); English only; jobs restricted to the
-- canonical set. Photos are NOT touched (none published without a logged consent record).
--
-- Repo convention (cf. 0031): inserted at column-default publication_status = 'review'
-- (status 'active', tier 'editorial_seed') — in the catalogue but NOT public until an
-- operator flips to 'published'. Idempotent via `where not exists (slug)`.
-- Held OUT (needs_verification, not inserted): kurasu-bali (unconfirmed pop-up),
-- dapur-bali-mula (North Bali, outside guide districts). Production apply is a founder step.

begin;

-- ---------- canggu (6) ----------
insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$alma-tapas-bar$ob$, $ob$Alma Tapas Bar$ob$, $ob$restaurant$ob$, $ob$canggu$ob$, $ob$Jl. Pantai Berawa, Canggu (Berawa)$ob$, $ob$Jl. Pantai Berawa No.89C, Canggu, Kec. Kuta Utara, Kabupaten Badung, Bali 80361$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Alma%20Tapas%20Bar%20Canggu%20Berawa%20Bali$ob$, $ob$https://almatapasbar.com/$ob$, $ob$https://www.instagram.com/almatapasbar/$ob$, $ob$A neighbourhood Spanish tapas bar in Berawa built around shared plates, wine, sangria and vermouth in a rustic, Mediterranean-styled room. The menu spans land, sea and garden small plates meant to be ordered across the table.$ob$, $ob$shared plates with wine; casual date over tapas; small group grazing; unhurried evening in canggu$ob$, $ob$anyone wanting a fast solo bite or a single large main course$ob$, $ob$patatas bravas; chorizo al vino; pulpo a la gallega (octopus); tortilla española; grilled prawns; sangria or vermouth$ob$, $ob$$$$$ob$, array['group_dinner_share','date_night_special']::text[]
where not exists (select 1 from venues where slug = $ob$alma-tapas-bar$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$home-by-chef-wayan$ob$, $ob$HOME by Chef Wayan$ob$, $ob$restaurant$ob$, $ob$canggu$ob$, $ob$Pererenan, Canggu$ob$, $ob$Jl. Pantai Pererenan No. 92, Pererenan, Kec. Mengwi, Kabupaten Badung, Bali 80351$ob$, $ob$https://maps.app.goo.gl/mET5aM7JhTn8TbwW8$ob$, $ob$https://bychefwayan.com/$ob$, $ob$https://www.instagram.com/home.by.chefwayan/$ob$, $ob$Modern Balinese cooking from Chef Wayan Kresna Yasa in a seaside Pererenan setting, reworking family and island recipes with contemporary technique. The kitchen is spice- and produce-driven and keeps a full vegan section alongside its seafood and traditional dishes.$ob$, $ob$a considered balinese dinner; introducing someone to indonesian flavours done well; a table mixing meat, seafood and vegan diners$ob$, $ob$travellers wanting a cheap warung price point; anyone after generic western comfort food$ob$, $ob$bebek betutu; babi guling; ayam srosop; braised lettuce with tempe crumble$ob$, $ob$$$$$ob$, array['date_night_special','special_occasion','local_food_calm']::text[]
where not exists (select 1 from venues where slug = $ob$home-by-chef-wayan$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$hungry-bird-coffee$ob$, $ob$Hungry Bird Coffee Roaster$ob$, $ob$cafe$ob$, $ob$canggu$ob$, $ob$Tibubeneng, Canggu$ob$, $ob$Jl. Segara Perancak No.86, Tibubeneng, Kuta Utara, Badung Regency, Bali 80361, Indonesia$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Hungry%20Bird%20Coffee%20Roaster%20Canggu%20Bali$ob$, $ob$https://www.coffeeinsurrection.com/hungry-bird-coffee-roaster.html$ob$, $ob$https://www.instagram.com/hungrybirdcoffee/$ob$, $ob$A specialty coffee roastery that has roasted its own beans since 2013, working directly with local farms, paired with an all-day brunch kitchen. The house blends and single origins are the reason to come, with a laptop-friendly room to linger in.$ob$, $ob$coffee-led brunch; laptop work and long stays; post-surf breakfast; buying house-roasted beans$ob$, $ob$late-night plans, as the kitchen closes in the afternoon; a big shared sit-down dinner$ob$, $ob$house-roasted espresso and filter coffee; banana pancakes; naughty monkey bowl$ob$, $ob$$$$ob$, array['brunch_after_surf','quiet_work_cafe']::text[]
where not exists (select 1 from venues where slug = $ob$hungry-bird-coffee$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$secret-spot-bali$ob$, $ob$Secret Spot$ob$, $ob$cafe$ob$, $ob$canggu$ob$, $ob$Canggu (Jl. Tanah Barak)$ob$, $ob$Jl. Tanah Barak No. 7, Canggu, Kec. Kuta Utara, Kabupaten Badung, Bali 80361$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Secret%20Spot%20Canggu%20Tanah%20Barak%20Bali$ob$, $ob$https://www.instagram.com/secretspot.bali/$ob$, $ob$https://www.instagram.com/secretspot.bali/$ob$, $ob$A fully plant-based cafe serving vegan breakfast through dinner, with vegan croissants, bowls, curries and ramen, plus coffee roasted weekly on the island. Extras like Monday pasta nights with live jazz and a chicory coffee alternative round out the character.$ob$, $ob$vegan breakfast and brunch; plant-based croissants and pastries; island-roasted coffee; relaxed all-day dining$ob$, $ob$diners set on meat or seafood dishes; anyone wanting a fast grab-and-go stop$ob$, $ob$vegan croissants; pesto and cheeze croissant; pancakes; full English breakfast; vegan bowls and curries; chicory coffee$ob$, $ob$$$$ob$, array['brunch_after_surf','quiet_work_cafe']::text[]
where not exists (select 1 from venues where slug = $ob$secret-spot-bali$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$sushimi-bali$ob$, $ob$Sushimi Bali$ob$, $ob$restaurant$ob$, $ob$canggu$ob$, $ob$Canggu (Berawa)$ob$, $ob$Jl. Pantai Berawa No.101C, Tibubeneng, Kuta Utara, Badung Regency, Bali 80361, Indonesia$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Sushimi%20Berawa%20Canggu%20Bali$ob$, $ob$http://www.sushimibali.com/$ob$, $ob$https://www.instagram.com/sushimibali/$ob$, $ob$A sushi-train restaurant on Jl. Pantai Berawa serving classic and creative sushi and maki plus an izakaya-style a la carte range. The menu extends to poke bowls, donburi, sushi burritos and sushi donuts, with gluten-free, vegan and vegetarian options.$ob$, $ob$casual sushi with friends; interactive sushi-train dining; solo diners; mixed dietary groups$ob$, $ob$a formal or high-end omakase occasion; a quiet intimate dinner; anyone wanting a sea view$ob$, $ob$sushi-train plates; maki rolls; poke bowls; donburi; sushi burrito$ob$, $ob$$$$ob$, array['group_dinner_share','just_landed_easy_dinner']::text[]
where not exists (select 1 from venues where slug = $ob$sushimi-bali$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$the-loft-bali$ob$, $ob$The Loft$ob$, $ob$cafe$ob$, $ob$canggu$ob$, $ob$Batu Bolong, Canggu$ob$, $ob$Jl. Pantai Batu Bolong No. 50A, Canggu, Kec. Kuta Utara, Kabupaten Badung, Bali 80361$ob$, $ob$https://www.google.com/maps/place/The+Loft+Canggu/@-8.6509484,115.1334429,17z/data=!3m1!4b1!4m5!3m4!1s0x2dd2387eacbd2f6d:0xa70ea493a2c5a8d0!8m2!3d-8.6509484!4d115.1356316$ob$, $ob$https://linktr.ee/theloftbali$ob$, $ob$https://www.instagram.com/theloftbali/$ob$, $ob$A Bondi-inspired all-day brunch cafe on Batu Bolong with specialty coffee and a large plant-based selection. It leans to healthy breakfast staples, bowls and toasts in a relaxed Canggu setting.$ob$, $ob$a slow brunch after the beach; specialty coffee and a laptop; plant-based and healthy breakfast eaters$ob$, $ob$anyone seeking a quiet non-touristy local spot or a traditional balinese meal$ob$, $ob$dragon fruit smoothie bowl; coconut pancakes; avocado on toast with poached eggs; matcha latte$ob$, $ob$$$$ob$, array['brunch_after_surf','quiet_work_cafe']::text[]
where not exists (select 1 from venues where slug = $ob$the-loft-bali$ob$);

-- ---------- denpasar (2) ----------
insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$ayam-betutu-khas-gilimanuk$ob$, $ob$Ayam Betutu Khas Gilimanuk$ob$, $ob$restaurant$ob$, $ob$denpasar$ob$, $ob$Renon, Jl. Merdeka, Denpasar$ob$, $ob$Jl. Merdeka No. 88, Renon, Denpasar Timur, Kota Denpasar, Bali 80235$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Ayam%20Betutu%20Khas%20Gilimanuk%20Merdeka%20Renon%20Denpasar%20Bali$ob$, $ob$http://betutugilimanuk.com/$ob$, $ob$https://www.instagram.com/ayambetutugilimanuk_/$ob$, $ob$A long-running Denpasar specialist in ayam betutu, the Gilimanuk-style chicken slow-cooked in Balinese spice paste until it falls off the bone. It is a focused, no-frills local kitchen where the betutu and the sambals are the whole point.$ob$, $ob$trying a genuine balinese classic; a spice-forward local lunch; eating where residents eat away from the tourist strip$ob$, $ob$people avoiding chilli or wanting mild flavours; anyone after a western menu, cocktails or a scenic view$ob$, $ob$ayam betutu; nasi campur ayam betutu; plecing kangkung; sambal matah$ob$, $ob$$$ob$, array['local_food_calm','family_early_dinner']::text[]
where not exists (select 1 from venues where slug = $ob$ayam-betutu-khas-gilimanuk$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$warung-wardani$ob$, $ob$Warung Wardani$ob$, $ob$warung$ob$, $ob$denpasar$ob$, $ob$Denpasar (Jl. Yudistira)$ob$, $ob$Jl. Yudistira No.2, Dangin Puri Kauh, Kec. Denpasar Utara, Kota Denpasar, Bali 80232$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Warung%20Wardani%20Yudistira%20Denpasar%20Bali$ob$, null, $ob$https://www.instagram.com/warungwardanibali/$ob$, $ob$A decades-old Denpasar warung known for nasi campur Bali, plated with items such as satay, dendeng and vegetables over rice. It is a longtime local institution also recognised for serving halal Balinese food, open daytime only.$ob$, $ob$authentic Balinese nasi campur; quick local lunch; halal Balinese food; solo or budget dining$ob$, $ob$dinner or late-night meals; alcohol and a bar scene; an upscale or scenic setting$ob$, $ob$nasi campur Bali; nasi kare; gado-gado; soto ayam; soto daging$ob$, $ob$$$ob$, array['local_food_calm']::text[]
where not exists (select 1 from venues where slug = $ob$warung-wardani$ob$);

-- ---------- jimbaran (1) ----------
insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$menega-cafe$ob$, $ob$Menega Cafe$ob$, $ob$restaurant$ob$, $ob$jimbaran$ob$, $ob$Jimbaran (Muaya Beach)$ob$, $ob$Muaya Beach (Pantai Muaya), Jimbaran, Kec. Kuta Selatan, Kabupaten Badung, Bali 80361$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Menega%20Cafe%20Muaya%20Beach%20Jimbaran%20Bali$ob$, null, null, $ob$A long-running Jimbaran Bay seafood cafe where you pick fresh seafood by weight from the display and it is grilled over coconut-husk fires. Tables sit directly on Muaya Beach for toes-in-the-sand dining at sunset.$ob$, $ob$beachfront seafood dinner; sunset over the bay; groups sharing a seafood spread; special evening out$ob$, $ob$budget quick bites; vegetarians seeking variety; anyone wanting a quiet or air-conditioned room$ob$, $ob$grilled red snapper; butter prawns; crab in Padang sauce; grilled lobster$ob$, $ob$$$$$ob$, array['sunset_drinks_view','group_dinner_share','special_occasion']::text[]
where not exists (select 1 from venues where slug = $ob$menega-cafe$ob$);

-- ---------- seminyak (7) ----------
insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$bossman-burgers$ob$, $ob$BO$$MAN$ob$, $ob$restaurant$ob$, $ob$seminyak$ob$, $ob$Seminyak (Jl. Kayu Cendana)$ob$, $ob$Jl. Kayu Cendana No. 8B, Seminyak, Kec. Kuta Utara, Kabupaten Badung, Bali 80361$ob$, $ob$https://www.google.com/maps/search/?api=1&query=BOSSMAN%20Burgers%20Kayu%20Cendana%20Seminyak%20Bali$ob$, $ob$https://bossmanbali.com/$ob$, $ob$https://www.instagram.com/bossmanbali/$ob$, $ob$A Seminyak burger joint built on Australian-beef smash and gourmet patties with house-made sauces and freshly baked buns. It runs late, serving until roughly 5am, which makes it a reliable post-night-out stop.$ob$, $ob$late-night cravings; casual meat-forward meals; after a night out; quick group bite$ob$, $ob$a quiet, refined sit-down dinner; anyone avoiding meat-heavy fare$ob$, $ob$Original Gangster; Al Capone; Lucky Pig; smash burger; chicken sando$ob$, $ob$$$$ob$, array['just_landed_easy_dinner','group_dinner_share']::text[]
where not exists (select 1 from venues where slug = $ob$bossman-burgers$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$expat-roasters$ob$, $ob$Expat. Roasters$ob$, $ob$cafe$ob$, $ob$seminyak$ob$, $ob$Seminyak (Petitenget)$ob$, $ob$Jl. Petitenget No. 1A, Kerobokan Kelod, Kec. Kuta Utara, Kabupaten Badung, Bali 80361$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Expat%20Roasters%20Petitenget%20Seminyak%20Bali$ob$, $ob$https://expatroasters.com/$ob$, null, $ob$A specialty coffee roastery and cafe that sources and roasts its own beans, working directly with Indonesian producers including farms near the roastery. Single-origin Indonesian brews like Bali Kintamani sit alongside a small menu of light bites.$ob$, $ob$serious coffee lovers; single-origin tasting; laptop-friendly morning work; buying beans and brew gear$ob$, $ob$a full sit-down meal; a lively bar or nightlife scene; anyone after a beach or view setting$ob$, $ob$single-origin Bali Kintamani; espresso and macchiato; tuna toastie; ham and cheese toastie$ob$, $ob$$$$ob$, array['quiet_work_cafe']::text[]
where not exists (select 1 from venues where slug = $ob$expat-roasters$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$gusto-gelato$ob$, $ob$Gusto Gelato & Caffe$ob$, $ob$cafe$ob$, $ob$seminyak$ob$, $ob$Jl. Mertanadi, Kerobokan (Seminyak)$ob$, $ob$Jl. Mertanadi No.46B, Kerobokan Kelod, Kec. Kuta Utara, Kabupaten Badung, Bali 80361, Indonesia$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Gusto%20Gelato%20Caffe%20Mertanadi%20Kerobokan%20Bali$ob$, $ob$https://gusto-gelateria.com/$ob$, $ob$https://www.instagram.com/gustogelatocaffe/$ob$, $ob$An artisan gelateria and caffe turning out house-made gelato in a wide flavour range, from classic fior di latte to local twists like lemongrass, ginger and sesame. It also pours proper coffee in a calm sit-down space.$ob$, $ob$afternoon dessert stop; cooling off in the heat; family treat with kids; coffee-and-gelato pause$ob$, $ob$anyone looking for a full sit-down meal or dinner service$ob$, $ob$fior di latte; gianduia; pistachio; seasonal local flavours (lemongrass, ginger, sesame); espresso alongside$ob$, $ob$$ · small cup/cone ~40K, medium ~70K$ob$, array['local_food_calm','family_early_dinner']::text[]
where not exists (select 1 from venues where slug = $ob$gusto-gelato$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$motel-mexicola$ob$, $ob$Motel Mexicola$ob$, $ob$restaurant$ob$, $ob$seminyak$ob$, $ob$Jl. Kayu Jati, Petitenget (Seminyak)$ob$, $ob$Jl. Kayu Jati No.9, Petitenget, Seminyak, Kuta, Badung Regency, Bali 80361, Indonesia$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Motel%20Mexicola%20Seminyak%20Bali$ob$, $ob$https://motelmexicola.info/$ob$, $ob$https://www.instagram.com/motelmexicola/$ob$, $ob$A high-energy Mexican cantina in Petitenget known for sharing-style street food, a big tequila and mezcal list, and a colourful, music-driven room that turns into a party as the night goes on. Food and drinks are built for a lively group table.$ob$, $ob$group night out; birthdays and celebrations; loud and social dinner; cocktails and dancing$ob$, $ob$anyone after a quiet, low-key or romantic meal$ob$, $ob$pork al pastor tacos; beer-battered fish tacos; ceviche; chargrilled corn; margaritas; mezcal cocktails$ob$, $ob$$$$$ob$, array['group_dinner_share','sunset_drinks_view']::text[]
where not exists (select 1 from venues where slug = $ob$motel-mexicola$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$nalu-bowls$ob$, $ob$Nalu Bowls$ob$, $ob$cafe$ob$, $ob$seminyak$ob$, $ob$Jl. Drupadi, Seminyak$ob$, $ob$Jl. Drupadi 1 No.2A, Seminyak, Kec. Kuta, Kabupaten Badung, Bali 80361$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Nalu%20Bowls%20Seminyak%20Drupadi%20Bali$ob$, $ob$https://nalubowls.com/$ob$, $ob$https://www.instagram.com/nalubowls/$ob$, $ob$A compact smoothie-bowl specialist whose bowls are each named after a famous surf break and built from tropical fruit, house granola and simple toppings. It is a grab-and-go healthy breakfast spot rather than a sit-down cafe.$ob$, $ob$a fast healthy breakfast; a post-beach refuel; a light fruit-based bite on the go$ob$, $ob$anyone wanting a full cooked brunch, a long laptop session or a large dining room$ob$, $ob$uluwatu bowl; pina colada bowl; strawberry banana smoothie$ob$, $ob$$$$ob$, array['brunch_after_surf','local_food_calm']::text[]
where not exists (select 1 from venues where slug = $ob$nalu-bowls$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$saigon-street$ob$, $ob$Saigon Street$ob$, $ob$restaurant$ob$, $ob$seminyak$ob$, $ob$Jl. Petitenget, Seminyak$ob$, $ob$Jl. Petitenget No. 77X, Kerobokan, Kec. Kuta Utara, Kabupaten Badung, Bali 80361$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Saigon%20Street%20Petitenget%20Seminyak%20Bali$ob$, $ob$https://www.facebook.com/saigonstreetbali/$ob$, null, $ob$A design-forward Vietnamese restaurant in the Petitenget dining strip, serving modern takes on classic and regional dishes alongside a late cocktail bar. Plates are built for sharing in a vivid, colourful interior.$ob$, $ob$shared plates with cocktails; lively date night; group dinner out; a design-led dinner setting$ob$, $ob$a quiet, low-key intimate meal; travellers after the cheapest street-food price point$ob$, $ob$pho bo with wagyu beef; steamed bao buns; dumplings; fresh rolls and wraps$ob$, $ob$$$$$ob$, array['date_night_special','group_dinner_share']::text[]
where not exists (select 1 from venues where slug = $ob$saigon-street$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$vincent-nigita$ob$, $ob$Vincent Nigita$ob$, $ob$cafe$ob$, $ob$seminyak$ob$, $ob$Seminyak (Jl. Petitenget, Kanvaz resort)$ob$, $ob$Kanvaz Village Resort, Jl. Petitenget No. 188, Seminyak, Kec. Kuta Utara, Kabupaten Badung, Bali 80361$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Kanvaz%20Patisserie%20Vincent%20Nigita%20Petitenget%20Seminyak%20Bali$ob$, $ob$https://vincentnigita.com/$ob$, $ob$https://www.instagram.com/kanvazpatisserievincentnigita/$ob$, $ob$A French patisserie inside Kanvaz resort from Bordeaux-trained pastry chef Vincent Nigita, pairing classical French technique with Indonesian flavours. Classic pastries sit alongside a weekend tea-room experience of plated desserts.$ob$, $ob$afternoon pastry and tea; a sweet treat with care; a calm indulgent pause; a special sweet moment$ob$, $ob$a full savoury meal or a budget-casual bite; those after a quick grab-and-go snack$ob$, $ob$Paris-Brest; Saint Honore; chocolate eclair; Japanese fan creations; weekend tea-room dessert experience$ob$, $ob$$$$$ob$, array['special_occasion','date_night_special']::text[]
where not exists (select 1 from venues where slug = $ob$vincent-nigita$ob$);

-- ---------- ubud (6) ----------
insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$bebek-bengil$ob$, $ob$Bebek Bengil$ob$, $ob$restaurant$ob$, $ob$ubud$ob$, $ob$Jl. Hanoman, Padang Tegal, Ubud$ob$, $ob$Jl. Hanoman, Padang Tegal, Ubud, Gianyar Regency, Bali 80571, Indonesia$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Bebek%20Bengil%20Dirty%20Duck%20Diner%20Padang%20Tegal%20Ubud%20Bali$ob$, $ob$https://www.bebekbengil.co.id/en$ob$, $ob$https://www.instagram.com/bebekbengilrestaurant/$ob$, $ob$The Ubud restaurant that popularised Balinese-style crispy duck, open since 1990, set among rice-paddy garden pavilions. The duck is steamed in Indonesian spices then deep-fried until the skin crackles while the meat stays tender.$ob$, $ob$first taste of balinese crispy duck; rice-paddy garden dinner; groups sharing regional dishes; visitors near monkey forest$ob$, $ob$diners who want a quiet hidden local warung; vegetarians, since the menu centres on duck and meat$ob$, $ob$crispy duck (bebek bengil); duck satay; smoked duck (order a day ahead)$ob$, $ob$$$$ob$, array['family_early_dinner','group_dinner_share']::text[]
where not exists (select 1 from venues where slug = $ob$bebek-bengil$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$kilig-bali$ob$, $ob$Kilig Bali$ob$, $ob$restaurant$ob$, $ob$ubud$ob$, $ob$Ubud (Jl. Raya Goa Gajah, Peliatan)$ob$, $ob$Jl. Raya Goa Gajah No.94, Peliatan, Ubud, Kec. Ubud, Kabupaten Gianyar, Bali 80582$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Kilig%20Filipino%20Warung%20Ubud%20Bali$ob$, $ob$https://kiligbali.com$ob$, $ob$https://www.instagram.com/kiligbali/$ob$, $ob$A Filipino warung in Peliatan set in a bamboo hut with rice-field views, cooking home-style Filipino comfort food. It stands out as a dedicated Filipino kitchen in an area dominated by Balinese and Western menus.$ob$, $ob$filipino comfort food; calm rice-field setting; shared table meals; family dinner$ob$, $ob$a quick central-Ubud stop given the Peliatan location; anyone avoiding rich, pork-forward dishes$ob$, $ob$adobo; sisig; lechon belly roll; sinigang; kinilaw; halo-halo; leche flan$ob$, $ob$$$$ob$, array['local_food_calm','family_early_dinner','group_dinner_share']::text[]
where not exists (select 1 from venues where slug = $ob$kilig-bali$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$melting-wok-warung$ob$, $ob$Melting Wok Warung$ob$, $ob$restaurant$ob$, $ob$ubud$ob$, $ob$Ubud (Jl. Gootama)$ob$, $ob$Jl. Gootama No.13, Ubud, Kec. Ubud, Gianyar Regency, Bali 80571, Indonesia$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Melting%20Wok%20Warung%20Jalan%20Gootama%20Ubud%20Bali$ob$, $ob$https://www.instagram.com/melting_wok_warung/$ob$, $ob$https://www.instagram.com/melting_wok_warung/$ob$, $ob$A tiny eight-table warung run by a French-Laotian couple, serving fragrant coconut curries, stir-fries and crepes off a short blackboard menu that changes daily. The Laotian herbs and French dessert touches make it distinct from standard Ubud warungs.$ob$, $ob$an intimate dinner; herb-forward coconut curries; a short curated menu; foodies after fusion flavour$ob$, $ob$large groups; walk-ins without a booking; anyone needing a wide menu or fast turnover$ob$, $ob$tempeh coconut curry with rice noodles; coconut curries; dumplings; chicken crepe; coco crepe with brown sugar and coconut cream$ob$, $ob$$$$ob$, array['date_night_special','local_food_calm']::text[]
where not exists (select 1 from venues where slug = $ob$melting-wok-warung$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$sayuri-healing-food$ob$, $ob$Sayuri Healing Food$ob$, $ob$cafe$ob$, $ob$ubud$ob$, $ob$Ubud (Peliatan)$ob$, $ob$Jl. Sukma Kesuma No.2, Peliatan, Ubud, Gianyar Regency, Bali 80571, Indonesia$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Sayuri%20Healing%20Food%20Peliatan%20Ubud%20Bali$ob$, $ob$https://sayurihealingfood.com/$ob$, $ob$https://www.instagram.com/sayuri_healing_food/$ob$, $ob$A raw-vegan and plant-based cafe in central Ubud focused on living-food cooking, cold-pressed juices and a rotating case of raw desserts, with an attached plant-based academy. The kitchen leans into raw preparation rather than standard cooked vegan fare.$ob$, $ob$plant-based and raw eating; relaxed daytime meals; wellness-minded visitors; long cafe sits$ob$, $ob$committed meat-eaters; anyone wanting a fast, familiar hearty meal$ob$, $ob$raw lasagna; Life is a Blessing cake; smoothie bowls; raw cheesecake; cold-pressed juices$ob$, $ob$$$$ob$, array['local_food_calm','quiet_work_cafe']::text[]
where not exists (select 1 from venues where slug = $ob$sayuri-healing-food$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$tukies-coconut-shop$ob$, $ob$Tukies Coconut Shop$ob$, $ob$cafe$ob$, $ob$ubud$ob$, $ob$Jl. Monkey Forest, Ubud$ob$, $ob$Jl. Monkey Forest No.15, Ubud, Gianyar Regency, Bali 80571, Indonesia$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Tukies%20Coconut%20Shop%20Monkey%20Forest%20Ubud%20Bali$ob$, $ob$https://www.facebook.com/tukies.online/$ob$, $ob$https://www.instagram.com/tukiescoconutshop/$ob$, $ob$A coconut-focused dessert and drinks shop where everything is built around fresh coconut, including vegan coconut ice cream served in the shell with roasted coconut curls. A quick, cooling stop in central Ubud.$ob$, $ob$a cooling coconut treat while walking ubud; vegan dessert; quick sweet break; fresh coconut drinks$ob$, $ob$a full sit-down meal or savoury dinner; anyone avoiding coconut$ob$, $ob$coconut ice cream in the shell; coconut affogato; fresh coconut water$ob$, $ob$$$ob$, array['local_food_calm']::text[]
where not exists (select 1 from venues where slug = $ob$tukies-coconut-shop$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$warung-biah-biah$ob$, $ob$Warung Biah Biah$ob$, $ob$warung$ob$, $ob$ubud$ob$, $ob$Ubud (Jl. Gootama)$ob$, $ob$Jl. Goutama Sel. No.13, Ubud, Kecamatan Ubud, Kabupaten Gianyar, Bali 80571, Indonesia$ob$, $ob$https://www.google.com/maps/place/Warung+Biah+Biah/@-8.5093263,115.2620118,17z/data=!3m1!4b1!4m5!3m4!1s0x2dd23d6bba632509:0x6d31d114697259f4!8m2!3d-8.5093401!4d115.2642563$ob$, $ob$https://www.facebook.com/warungbiahbiah/$ob$, $ob$https://www.instagram.com/warung_biahbiah/$ob$, $ob$A long-running home-style Balinese warung open since 2002, serving authentic nasi campur and local classics at warung prices. Known for its house chili sauce and a spread of Balinese sides.$ob$, $ob$authentic Balinese food; budget local dining; nasi campur; a casual central Ubud meal$ob$, $ob$diners wanting a quiet or upscale setting; groups needing lots of space during busy peak hours$ob$, $ob$nasi campur; balinese tapas; mie goreng; soto ayam; nasi goreng$ob$, $ob$$$ob$, array['local_food_calm','just_landed_easy_dinner']::text[]
where not exists (select 1 from venues where slug = $ob$warung-biah-biah$ob$);

-- ---------- uluwatu-bukit (2) ----------
insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$drifter-surf-cafe$ob$, $ob$Drifter Surf Shop & Cafe$ob$, $ob$cafe$ob$, $ob$uluwatu-bukit$ob$, $ob$Uluwatu (Jl. Labuansait), Bukit$ob$, $ob$Jl. Labuansait No.52, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361$ob$, $ob$https://www.google.com/maps/search/?api=1&query=Drifter%20Surf%20Shop%20Cafe%20Uluwatu%20Bali$ob$, $ob$https://driftersurf.com/pages/cafe$ob$, $ob$https://www.instagram.com/driftersurfshop/$ob$, $ob$A healthy all-day cafe built inside Drifter's surf-lifestyle store, open since 2008 and set in an open-air Javanese limasan with rotating art. The kitchen leans clean and local, from plant-based to pescatarian, alongside specialty coffee from Sumatra.$ob$, $ob$post-surf refuel; healthy breakfast; specialty coffee; browsing surf gear over a long lunch$ob$, $ob$travellers wanting a traditional Balinese warung experience; anyone after a quiet fine-dining setting rather than a busy surf-shop cafe$ob$, $ob$smoothie bowls; brekkie burrito; toasts; cold-pressed juices; Mandailing coffee$ob$, $ob$$$$ob$, array['brunch_after_surf','quiet_work_cafe']::text[]
where not exists (select 1 from venues where slug = $ob$drifter-surf-cafe$ob$);

insert into venues (id, slug, name, category, district, area, address, gmaps_url, official_url, instagram_url, why_its_here, best_for, not_for, what_to_order, price_anchor, jobs)
select gen_random_uuid()::text, $ob$the-cashew-tree$ob$, $ob$The Cashew Tree$ob$, $ob$cafe$ob$, $ob$uluwatu-bukit$ob$, $ob$Bingin, Uluwatu (Bukit)$ob$, $ob$Jl. Pantai Bingin No.9, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361$ob$, $ob$https://www.google.com/maps/place/The+Cashew+Tree/@-8.8084415,115.112652,17z/data=!4m6!3m5!1s0x2dd245479b8f1853:0xc76fa2acc632056a!8m2!3d-8.8069026!4d115.1170434!16s/g/11byck_jvr$ob$, null, $ob$https://www.instagram.com/thecashewtree.collective/$ob$, $ob$A relaxed, vegetarian-leaning cafe set in a leafy open-air space near Bingin, serving wholesome all-day plates and hosting weekly live-music nights. It doubles as a social hub with regular Thursday music and a fitness/yoga community on site.$ob$, $ob$post-surf brunch near bingin; healthy plant-forward meal; laid-back live-music night; casual group hang$ob$, $ob$anyone wanting a formal, fine-dining or meat-forward dinner$ob$, $ob$the soul bowl; corn fritters; quesadillas; fresh juices and smoothies; vegan cakes and desserts$ob$, $ob$$$$ob$, array['brunch_after_surf','group_dinner_share']::text[]
where not exists (select 1 from venues where slug = $ob$the-cashew-tree$ob$);

commit;
