-- Ubud verified restaurant cards (2026-07-23)
-- Only official-source-backed candidates with address, hours and editorial
-- decision fields are included. They remain review until a concrete Maps
-- entity URL is recorded; this migration never publishes a provisional search
-- link. Rows with open hotel/field/status gates stay in the candidate CSV.

insert into venues (
  id, slug, name, category, district, area, address, gmaps_url,
  official_url, tier, status, publication_status, price_anchor,
  opening_hours, why_its_here, best_for, not_for, what_to_order,
  jobs, last_verified_at
)
select gen_random_uuid()::text, v.slug, v.name, 'restaurant', 'ubud', v.area,
  v.address, v.gmaps_url, v.official_url, 'editorial_seed', 'active',
  'review', v.price_anchor, v.opening_hours, v.why_its_here, v.best_for,
  v.not_for, v.what_to_order, array[v.jobs]::text[], date '2026-07-23'
from (values
  ('akar-ubud','Akar Ubud','Tegallalang / Kedisan','Cebok Main Road, Kedisan, Tegallalang, Ubud, Gianyar 80561','https://www.google.com/maps/search/?api=1&query=Akar+Ubud','https://www.akarubud.com/','$$$','Breakfast 07:00-11:00; dinner 17:00-00:00 daily','A jungle-setting restaurant north of Ubud with a clear breakfast-and-dinner decision and a special-occasion atmosphere.','Travellers looking for jungle views and a destination dinner.','People wanting a central Ubud walk-in lunch.','Chef-led dinner menu and breakfast','special_occasion'),
  ('mori-ubud','Mori Ubud','Bisma','Jalan Bisma No.68, Ubud, Gianyar 80571','https://www.google.com/maps/search/?api=1&query=Mori+Ubud','https://www.moriubud.com/','$$$$','18:00 until finish daily','Japanese fine dining and teppanyaki in central Ubud, with local produce and Japanese proteins.','Special-occasion diners choosing Japanese fine dining in Ubud.','Budget diners or people seeking a quick daytime meal.','Teppanyaki set menu','special_occasion'),
  ('room-4-dessert','Room 4 Dessert','Sanggingan / Kedewatan','Jl. Raya Sanggingan, Kedewatan, Ubud, Gianyar 80561','https://www.google.com/maps/search/?api=1&query=Room+4+Dessert+Ubud','https://www.room4dessert.com/the-restaurant/','$$$$','16:00-22:00; closed Monday','A dedicated dessert tasting experience rather than a general restaurant, making the decision and format unusually clear.','Dessert-focused tasting menus and a planned evening experience.','Anyone wanting a conventional lunch or quick dessert stop.','21-course dessert tasting','special_occasion'),
  ('pica-south-american-kitchen','Pica South American Kitchen','Ubud Center','Jl. Dewisita No.2C, Ubud, Gianyar 80571','https://www.google.com/maps/search/?api=1&query=Pica+South+American+Kitchen+Ubud','https://picabali.com/','$$$','18:00-22:00 daily','A small South American kitchen in central Ubud with a distinctive cuisine angle absent from most local lists.','Diners seeking Peruvian and South American flavours in Ubud.','People looking for Balinese food or a large family room.','Ceviche and South American sharing plates','date_night_special'),
  ('moksa','Moksa','Sayan','Sayan, Ubud, Bali','https://www.google.com/maps/search/?api=1&query=Moksa+Ubud','https://moksaubud.com/','$$','09:00-21:00 daily','A plant-based restaurant with a permaculture garden and farm-to-table identity in Sayan.','Plant-based diners seeking a destination meal and garden setting.','Visitors wanting meat-heavy or central Ubud nightlife dining.','Plant-based chef recommendations','local_food_calm'),
  ('herb-library','Herb Library','Ubud Center','Jl. Jembawan, Ubud, Gianyar, Bali 80571','https://www.google.com/maps/search/?api=1&query=Herb+Library+Ubud','https://www.herblibraryubud.com/','$$','07:00-23:00 daily','A contemporary all-day venue with plant-based dishes and responsibly sourced fish and chicken options.','Mixed-diet groups wanting healthy all-day dining.','People looking specifically for a traditional Balinese warung.','Seasonal plant-based dishes and catch of the day','just_landed_easy_dinner'),
  ('wild-vegan','Wild Vegan','Ubud Center','Jl. Sugriwa No.16, Ubud, Gianyar 80571','https://www.google.com/maps/search/?api=1&query=Wild+Vegan+Ubud','https://www.wildveganbali.com/','$$','10:00-22:00 daily','A 100% vegan restaurant with medicinal-plant and whole-food positioning in central Ubud.','Vegan and wellness-focused travellers.','Anyone looking for meat or alcohol-led dining.','Vegan whole-food menu','local_food_calm'),
  ('warung-semesta','Warung Semesta','Monkey Forest','Jl. Monkey Forest No.9, Ubud, Gianyar 80571','https://www.google.com/maps/search/?api=1&query=Warung+Semesta+Ubud','https://warungsemesta-ubud.com/','$$','07:30-22:30 daily','An organic, vegetarian and non-vegetarian restaurant on Monkey Forest Road.','Healthy mixed-diet meals near Monkey Forest.','Anyone needing a formal fine-dining experience.','Organic Indonesian dishes','local_food_calm'),
  ('bella-by-sage','Bella by Sage','Penestanan / Sayan','Jl. Penestanan, Sayan, Ubud, Gianyar 80571','https://www.google.com/maps/search/?api=1&query=Bella+by+Sage+Ubud','https://www.bellaubud.com/','$$','10:00-21:00 daily','A vegan plant-based kitchen in Penestanan with pizzas, pastas, salads and gluten-free accommodation.','Vegan, gluten-free and casual Italian-style dining.','People wanting a traditional local warung or fine dining tasting menu.','Vegan pizza, pasta and salads','family_early_dinner'),
  ('flourish','Flourish','Nyuh Kuning','1 Nyuh Kuning Rd, Ubud, Bali 80571','https://www.google.com/maps/search/?api=1&query=Flourish+Ubud','https://www.flourishbali.com/','$$','06:30-22:00 daily','A central healthy restaurant with explicit gluten-free and vegan positioning.','Early breakfast and gluten-free dining in Ubud.','People seeking cocktails or a luxury tasting menu.','Gluten-free breakfast and healthy lunch','brunch_after_surf'),
  ('bebek-tepi-sawah','Bebek Tepi Sawah','Teges / Peliatan','Banjar Teges, Jl. Raya Teges, Peliatan, Ubud, Gianyar 80571','https://www.google.com/maps/search/?api=1&query=Bebek+Tepi+Sawah+Ubud','https://bebektepisawah.com/','$$','10:00-22:00 daily','A rice-field restaurant built around crispy duck and traditional Balinese setting.','Family-friendly Balinese dining with a scenic setting.','People wanting a quick central-Ubud walk-in meal.','Crispy duck','family_early_dinner'),
  ('clear-cafe','Clear Café','Ubud Center','Jl. Hanoman No.8, Ubud, Bali 80571','https://www.google.com/maps/search/?api=1&query=Clear+Cafe+Ubud','https://clearcafebali.com/','$$','08:00-23:00; verify last order','A long-running healthy and international café on Hanoman with a clear wellness angle.','Healthy casual meals and café time in central Ubud.','People seeking a formal fine-dining experience.','Healthy Asian and international plates','quiet_work_cafe')
) as v(slug,name,area,address,gmaps_url,official_url,price_anchor,opening_hours,why_its_here,best_for,not_for,what_to_order,jobs)
where not exists (select 1 from venues existing where existing.slug = v.slug);
